version: "3.8"

services:
    cassandra:
        image: "cassandra:4.0"
        container_name: cassandra
        hostname: localhost
        environment:
            - "JVM_EXTRA_OPTS=-Xms2g -Xmx2g"
        ports:
            - "9042:9042"
